name: Basic Build

on:
  pull_request:

jobs:
    compile:
        name: Build N Operating system from current release
        runs-on: ubuntu-latest
        container:
          image: archlinux:latest
          options: --privileged
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Install and update packages
            run: pacman --noconfirm -Syyu archiso curl
          - name: Run the build process with Docker
            run: mkarchiso -v .
