name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install and update packages
        run: pacman --noconfirm -Syyu archiso curl
      - name: Run the build process with Docker
        run: mkarchiso -v .
      - name: Run ls
        run: ls
      - name: cd out
        run: cd out && mv *.iso os-release.iso
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: os-release.iso
          path: out/os-release.iso # or path/to/artifact

  release:
    needs: build
    name: Release an ISO
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: os-release.iso
          path: out/os-release.iso
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/os-release.iso
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true