name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install and update packages
        run: pacman --noconfirm -Syyu archiso curl
      - name: Run the build process with Docker
        run: mkarchiso -v .
      - name: Run ls
        run: ls
      - name: cd out
        run: cd out && ls
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: out/ # or path/to/artifact